load('//bazel:message_generation.bzl', 'generate_messages')

# genrule(
#     name='msgs',
#     srcs=glob(['msg/*.msg']),
#     outs=[
#         'sample.txt',
#     ],
#     cmd='$(location @genpy//:genmsg_py) > $@',
#     tools=['@genpy//:genmsg_py'],
# )

# generate_messages(
#     srcs=glob(['msg/*.msg']),
# )

# py_binary(
#     name='main',
#     srcs=['scripts/main.py'],
#     deps=[
#         ':msgs_py',
#     ],
# )

# load("//third_party/py:python_configure.bzl", "python_configure")