name: ros-bazel CI

on: push

jobs:
    build:
        # This is the host VM
        runs-on: ubuntu-18.04

        # And this is our custom Docker image
        container:
            image: nicolov/ros-bazel:0.0.3

        steps:
            - uses: actions/checkout@v1
            - name: build bazel
              run: |
                  bazel build //...

